# PostgreSQL (Render DB)
spring.datasource.url=jdbc:postgresql://dpg-d7b9khia214c739jc5n0-a:5432/workshop_db_me8o
spring.datasource.username=workshop_db_me8o_user
spring.datasource.password=PJgZJ6ZKmAnYkVjICE8HqtQ9CijT8kb4

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server port (Render uses 10000 automatically but this is safe)
server.port=8080
